test: Fix '-Werror=unused-variable' for non-debug build
Add (dummy) uses of the `NAME` and `X` params to the
non-debug-build version of the `TST_LOG_NAME` macro.

This fixes build failures like the following ones seen
in a GCC 13 build without the `--enable-debug` configure
option:

    WopiProofTests.cpp: In member function ‘void WopiProofTests::testCapiBlob()’:
    WopiProofTests.cpp:63:20: error: unused variable ‘testname’ [-Werror=unused-variable]
       63 |     constexpr auto testname = __func__;
          |                    ^~~~~~~~
    KitQueueTests.cpp: In member function ‘void KitQueueTests::testKitQueuePriority()’:
    KitQueueTests.cpp:77:20: error: unused variable ‘testname’ [-Werror=unused-variable]
       77 |     constexpr auto testname = __func__;
          |                    ^~~~~~~~
    KitQueueTests.cpp: In member function ‘void KitQueueTests::testTileCombinedRendering()’:
    KitQueueTests.cpp:125:20: error: unused variable ‘testname’ [-Werror=unused-variable]
      125 |     constexpr auto testname = __func__;
          |                    ^~~~~~~~
    KitQueueTests.cpp: In member function ‘void KitQueueTests::testTileRecombining()’:
    KitQueueTests.cpp:159:20: error: unused variable ‘testname’ [-Werror=unused-variable]
      159 |     constexpr auto testname = __func__;

Signed-off-by: Michael Weghorn <m.weghorn@posteo.de>
Change-Id: I99b969c28fa1d177bf23ca868aacda59f41b38ba