Add fallback if we failed to extract JSON in state change
Followup for commit d4c7aaa4c404323d51606c8d0789f8ec045f01f9
fixed master slide previews not being updated

Fix for:
1753887346547 INCOMING: statechanged: .uno:LanguageStatus=Englisch (Niederlande) {en-NL};en-NL
15:55:46.547 global.js:1 Exception SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2) emitting event statechanged: .uno:LanguageStatus=Englisch (Niederlande) {en-NL};en-NL
SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)
    at JSON.parse (<anonymous>)
    at NewClass._onStateChanged

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I4c466d3f24c9e830a4ddb6f806cdc6f814db24ac