slideshow: don't use invalid image
It fixes issue with case when we didn't get image for slide.
It could happen due to memory shortage?

Steps to reproduce:
1. Open some multi-slide complex presentation
2.  Play in window
3.  Quickly when presentation is loading new slide (black with spinning circle, or after a click to switch slide) click again on "present in window" in the main window

Result:
global.js:545 JSDialogBuilder: Unsupported control type: "modalpopup"
global.js:545 Exception TypeError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': Overload resolution failed. emitting event sliderenderingcomplete
TypeError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': Overload resolution failed.
    at RenderContextGl.loadTexture (http://localhost:9980/browser/0811262c/src/slideshow/RenderContext.js:53:12)
    at SlideRendererGl.createTexture (http://localhost:9980/browser/0811262c/src/slideshow/SlideRenderer.js:241:30)
    at SlideShowHandler.getTexture (http://localhost:9980/browser/0811262c/src/slideshow/engine/SlideShowHandler.js:642:35)

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: Ie1cbdf737b6c3bbecaba9d3f3f4676f828ff59a8