Fix build in UnitPerf
./common/Unit.hpp:488:18: error: 'UnitWSD::onDocumentLoaded' hides overloaded virtual function [-Werror,-Woverloaded-virtual]

caused by commit 6e790c63d0997094979b2a237f428ef7706e62ef
feat: Changes to UnitPerf measuring

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: Ib545b83e9d25cad08a6d2c92a7a1b19965621155