clang: fix unknown uint32_t error
fix build with clang 15 after commit e4b51310e268aa05ad83ea6ed79e92885b783eb6
wsd: header cleanup

In file included from common/SigUtil.cpp:14:
./common/SigUtil.hpp:117:50: error: unknown type name 'uint32_t'
    extern "C" { typedef void (*SigChildHandler)(uint32_t); }
                                                 ^

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I42020a2049e69693160eb92f49e7c89f5ba94a96