cypress: make image_operation_spec.js stable
Avoid:
CypressError: `cy.type()` failed because the page updated as a result of this command, but you tried to continue the command chain. The subject is no longer attached to the DOM, and Cypress cannot requery the page after commands such as `cy.type()`.

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: Ib061a952540d4bdc83247ba4e62c87423c5534ae