Fix build warning about mismatching declarations
Change required after commit 4d588e47e89323dd156d3922ba1ffd260651ce07
wsd: encapsulate the LockContext lockToken

Clang shows:

In file included from wsd/DocumentBroker.cpp:14:
./wsd/DocumentBroker.hpp:49:1: error: struct 'LockContext' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
struct LockContext;
^
./wsd/Storage.hpp:561:7: note: previous use is here
class LockContext final
      ^
./wsd/DocumentBroker.hpp:49:1: note: did you mean class here?
struct LockContext;
^~~~~~
class

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I70912d231e5913c350a439a9367eb7f377874a00