wsd: fix coplugin:capture
wsd/ClientSession.cpp:2024:64: error: function parameter captured by reference, capture by value instead [coplugin:capture]
                        << [&](auto& log) { Util::dumpHex(log, data); });
                                                               ^~~~

The checker assumes that all lambdas are long-living, and then capturing
'data' by reference is a problem. This is a debug log, just capture by
value instead of teaching the checker to ignore locations inside log
macros.

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I3b83c46ef4fa7b08fcf8d20a2206c1a653ee49ca