on reconnect of calc, annotations requested before geometry is available
this activate is called when we reconnect, but with the right timing we
can have no docLayer here, so we can't tell that this is calc, and so
end up requesting annotations without requesting calc geometry. The
annotations then arrive before geometry does and on positioning the
comments we fail with exception on use of the undefined geometry.

reproducible with:

make run-mobile spec=calc/annotation_spec.js

cy: command ✘  uncaught exception    TypeError: Cannot read properties of undefined (reading 'getCellRect')
    cy:command ✔ error:    Cannot read properties of undefined (reading 'getCellRect')
        TypeError: Cannot read properties of undefined (reading 'getCellRect')
          at NewClass._cellRangeToTwipRect (.../src/layer/tile/CanvasTileLayer.js:1032:53)
          at CommentSection.adjustCommentNormal (.../src/canvas/sections/CommentListSection.js:1362:79)
Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: I5c868bec008668a5f7f33c3e32d83f40b356c566