Fix clang build: unused WindowSize
net/DelaySocket.cpp:32:18: error: private field 'WindowSize' is not used [-Werror,-Wunused-private-field]
    const size_t WindowSize = 64 * 1024;

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I9de3bb823fca2ff0c0a8ed84fd97bf6af76f2381