Add an initial COOL-specific clang plugin
As suggested at
<https://github.com/CollaboraOnline/online/pull/10838#pullrequestreview-2527339319>,
detect some cases where capturing variables by reference in a lambda is
not safe, assuming that most lambdas are long-lived in coolwsd.

It would fail without commit
19861a2d0bdc2db9825f9d4b953ce3e0a7a3539b (kit, BackgroundSaveWatchdog:
fix memory management in the ctor, 2024-11-20) with the following
output:

kit/Kit.cpp:183:67: error: function parameter captured by reference, capture by value instead
                  Util::setThreadName("kitbgsv_" + Util::encodeId(mobileAppDocId, 3) + "_wdg");
                                                                  ^~~~~~~~~~~~~~
1 error generated.

And it would fail without commit
92efdebaeb3dae25eedb02801ac395ad6abf95dd (Fix memory handling in
Session::asyncConnect(), 2025-01-03) with the folliwng output:

./net/HttpRequest.hpp:1734:107: error: function parameter captured by reference, capture by value instead
            poll.addCallback([selfLifecycle = shared_from_this(), this, &poll, socket=std::move(socket), &result]() {
                                                                                                          ^~~~~~
1 error generated.

The clang API is nominally unstable, but this simple plugin seems to
work with openSUSE clang 15 and Fedora clang 19 without any ifdefs so
far.

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: Ic5b40198f9c6c192603395fec6d6522951cb535e