jsdialog: Pasting externally copied data in Calc can fail #6597
Fixes #6597

error:
Clipboard.js:305 Uncaught TypeError: this.isPasteSpecialDialogOpen is not a function
    at Clipboard.js:305:16
    at request.onload (Clipboard.js:225:6)

Regression from e116a4d3e8cbfb5b673e212822a17992c506da50

Signed-off-by: Aron Budea <aron.budea@collabora.com>
Change-Id: I8c2717b627fead7a3ad3bdd870845c86c586eed4