Fix for #10885 : uncaught typeerror when leaving
Possibly regression from commit 4512fc8f4064c1472c3c134e7e76cb1377fe6064
Move graphic selection related logic to its own file.

Socket.js:1680 Uncaught TypeError: this._map._docLayer._onUpdateGraphicSelection is not a function
    at NewClass._onSocketClose (Socket.js:1680:25)
_onSocketClose	@	Socket.js:1680

we don't have that function anymore

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I197d1da39b40168d99156fde5ebb951043f913d3