clang, test: cover SocketPoll subclass check
Fails with commit c525bf1d340ffa9e7318d0593c6c0553ca88766b (enforce
SocketPoll is created via shared_ptr, 2025-03-29) reverted:

error: 'error' diagnostics expected but not seen:
  File test/refcounting.cpp Line 28 (directive at test/refcounting.cpp:27): instance allocated on the stack, create it with std::shared_ptr [coplugin:refcounting]

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: I439cf2765d02b38c5b9e8794bb1febf8f848d7f5